# Generated by Django 5.0.3 on 2024-05-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_hdpo_escape'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdpo',
            name='Escape',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
