# Generated by Django 5.0.3 on 2024-05-01 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hdpo_escape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hdpo',
            name='Escape',
        ),
    ]
