# Generated by Django 5.0.3 on 2024-05-01 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_hdpo_escape'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdpo',
            name='DjangoTimeStamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 21, 9, 21, 773422)),
        ),
    ]
